# Generated by Django 4.1.3 on 2022-12-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pslug',
            new_name='slug',
        ),
    ]
